networks:
  media-net:
    external: true

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: zxy_pg
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: pg
    networks:
      - media-net
    ports:
      - "5696:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pg -d pg"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-server:
    image: redis:latest
    container_name: redis_stag
    command: redis-server --requirepass hackme
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - media-net
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    restart: always

  app:
    container_name: zxy_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    networks:
      - media-net
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .env:/app/.env
