
[Interface]
PrivateKey = QD7jczI+N1wdJlm73YS9XGe1qMTzT9dRfDDEQ3yYkWw=
Address = 10.8.0.5/24
DNS = 1.1.1.1

[Peer]
PublicKey = pb0aAVhPATmK6ywyOrUGQ/8lMA4b/JOLDBXVbVXiyTw=
PresharedKey = 96jA8WabTXNAAuehbqfYrO1GcZqXXkOfnQpnNMIdxos=
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = vpn.tooharsh.co.in:51820